# Generated by Django 2.2.6 on 2020-04-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Average_From_VAgrades',
        ),
        migrations.AddField(
            model_name='course',
            name='VAgradesavg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
