# Generated by Django 2.2.6 on 2020-04-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='VAgradesavg',
        ),
    ]
