# Generated by Django 3.0.3 on 2020-04-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0001_starter_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cumulativeGPA',
        ),
    ]
