# Generated by Django 2.2.6 on 2020-04-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singulargradeitem',
            name='whichCoursesAvgGradeIsThis',
        ),
        migrations.RemoveField(
            model_name='singulargradeitem',
            name='whichGradeCategorysAvgGradeIsThis',
        ),
        migrations.RemoveField(
            model_name='singulargradeitem',
            name='whichStudentsCumulativeGPAisThis',
        ),
        migrations.RemoveField(
            model_name='singulargradeitem',
            name='whichStudentsSemesterGPAisThis',
        ),
        migrations.AddField(
            model_name='course',
            name='avgGrade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avgGrade', to='gradetracker.SingularGradeItem'),
        ),
    ]
