# Generated by Django 2.2.6 on 2020-02-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avgFromVAgrades',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
