# Generated by Django 2.2.6 on 2020-04-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cumulativeCredits',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
