# Generated by Django 2.2.6 on 2020-04-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cumulativeCredits',
        ),
    ]
