# Generated by Django 2.2.6 on 2020-04-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='darkMode',
            field=models.BooleanField(default=False),
        ),
    ]
