# Generated by Django 2.2.6 on 2020-04-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cumulativeCredits',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
