# Generated by Django 2.2.6 on 2020-04-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Average_From_VAgrades',
            new_name='VAgradesavg',
        ),
    ]
