# Generated by Django 2.2.6 on 2020-04-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0002_auto_20200419_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='VAgradesavg',
            new_name='Average_From_VAgrades',
        ),
    ]
