# Generated by Django 3.0.3 on 2020-04-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0002_remove_singulargradeitem_didgradegoup'),
    ]

    operations = [
        migrations.AddField(
            model_name='singulargradeitem',
            name='didGradeGoUp',
            field=models.BooleanField(null=True),
        ),
    ]
