# Generated by Django 2.2.6 on 2020-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0002_remove_course_vagradesavg'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='VAgradesavg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
