# Generated by Django 2.2.6 on 2020-02-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0002_auto_20200224_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='gradeCategoryItBelongsTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gradetracker.GradeCategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='studentItBelongsTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='gradetracker.Student'),
        ),
        migrations.AlterField(
            model_name='gradecategory',
            name='courseItBelongsTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='gradetracker.Course'),
        ),
    ]
