# Generated by Django 2.2.6 on 2020-04-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0003_auto_20200419_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Average_From_VAgrades',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
