# Generated by Django 2.2.6 on 2020-04-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0003_auto_20200415_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='notifyStudentOrNot',
        ),
    ]
