# Generated by Django 2.2.6 on 2020-02-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0003_auto_20200224_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='gradePercentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
