# Generated by Django 2.2.6 on 2020-04-17 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0004_auto_20200417_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecategory',
            name='avgCategoryGrade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avgCategoryGrade', to='gradetracker.SingularGradeItem'),
        ),
    ]
