# Generated by Django 2.2.6 on 2020-03-02 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0004_auto_20200224_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingularGradeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradePercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datetimeWhenInputted', models.DateTimeField(auto_now_add=True)),
                ('didGradeGoUp', models.BooleanField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='gradePercentage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradetracker.SingularGradeItem'),
        ),
        migrations.AlterField(
            model_name='course',
            name='gradePercentage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradetracker.SingularGradeItem'),
        ),
        migrations.AlterField(
            model_name='gradecategory',
            name='gradePercentage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradetracker.SingularGradeItem'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cumulativeGPA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumGPA', to='gradetracker.SingularGradeItem'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semesterGPA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semGPA', to='gradetracker.SingularGradeItem'),
        ),
    ]
