# Generated by Django 2.2.6 on 2020-03-02 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0005_auto_20200302_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='gradePercentage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gradetracker.SingularGradeItem'),
        ),
        migrations.AlterField(
            model_name='course',
            name='gradePercentage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gradetracker.SingularGradeItem'),
        ),
        migrations.AlterField(
            model_name='gradecategory',
            name='gradePercentage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gradetracker.SingularGradeItem'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cumulativeGPA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cumGPA', to='gradetracker.SingularGradeItem'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semesterGPA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semGPA', to='gradetracker.SingularGradeItem'),
        ),
    ]
