# Generated by Django 3.0.3 on 2020-04-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0005_singulargradeitem_didgradegoup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cumulativeGPA',
        ),
    ]
