# Generated by Django 3.0.3 on 2020-04-22 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0006_remove_student_cumulativegpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cumulativeGPA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cumGPA', to='gradetracker.SingularGradeItem'),
        ),
    ]
