# Generated by Django 2.2.6 on 2020-03-02 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0006_auto_20200302_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='gradePercentage',
        ),
        migrations.RemoveField(
            model_name='gradecategory',
            name='gradePercentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cumulativeGPA',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semesterGPA',
        ),
        migrations.AddField(
            model_name='singulargradeitem',
            name='courseAverageGrade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseAvgGrade', to='gradetracker.Course'),
        ),
        migrations.AddField(
            model_name='singulargradeitem',
            name='gradeCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradeCategory', to='gradetracker.GradeCategory'),
        ),
        migrations.AddField(
            model_name='singulargradeitem',
            name='studentCumulativeGPA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cumGPA', to='gradetracker.Student'),
        ),
        migrations.AddField(
            model_name='singulargradeitem',
            name='studentSemesterGPA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semGPA', to='gradetracker.Student'),
        ),
    ]
