# Generated by Django 2.2.6 on 2020-03-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradetracker', '0009_auto_20200302_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singulargradeitem',
            old_name='whichCourseAvgGradeIsThis',
            new_name='whichCoursesAvgGradeIsThis',
        ),
    ]
